// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UniverseService.Data;

#nullable disable

namespace UniverseService.Migrations
{
    [DbContext(typeof(UniverseDbContext))]
    partial class UniverseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UniverseService.Models.Galaxy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Diameter")
                        .HasColumnType("double precision");

                    b.Property<double>("DistanceFromEarth")
                        .HasColumnType("double precision");

                    b.Property<bool>("HasBlackHole")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("StarCount")
                        .HasColumnType("double precision");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Galaxies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Diameter = 105700.0,
                            DistanceFromEarth = 0.0,
                            HasBlackHole = true,
                            Name = "Milky Way",
                            StarCount = 400.0,
                            Type = "Spiral"
                        },
                        new
                        {
                            Id = 2,
                            Diameter = 220000.0,
                            DistanceFromEarth = 2537000.0,
                            HasBlackHole = true,
                            Name = "Andromeda",
                            StarCount = 1000.0,
                            Type = "Spiral"
                        },
                        new
                        {
                            Id = 3,
                            Diameter = 60000.0,
                            DistanceFromEarth = 3000000.0,
                            HasBlackHole = false,
                            Name = "Triangulum",
                            StarCount = 40.0,
                            Type = "Spiral"
                        },
                        new
                        {
                            Id = 4,
                            Diameter = 14000.0,
                            DistanceFromEarth = 163000.0,
                            HasBlackHole = false,
                            Name = "Large Magellanic Cloud",
                            StarCount = 30.0,
                            Type = "Irregular"
                        },
                        new
                        {
                            Id = 5,
                            Diameter = 50000.0,
                            DistanceFromEarth = 29350000.0,
                            HasBlackHole = true,
                            Name = "Sombrero Galaxy",
                            StarCount = 800.0,
                            Type = "Elliptical"
                        });
                });

            modelBuilder.Entity("UniverseService.Models.Planet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("DistanceFromStar")
                        .HasColumnType("double precision");

                    b.Property<int?>("GalaxyId")
                        .HasColumnType("integer");

                    b.Property<bool>("HasAtmosphere")
                        .HasColumnType("boolean");

                    b.Property<double>("Mass")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("Radius")
                        .HasColumnType("double precision");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Planets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DistanceFromStar = 0.39000000000000001,
                            GalaxyId = 1,
                            HasAtmosphere = false,
                            Mass = 0.055,
                            Name = "Mercury",
                            Radius = 2439.6999999999998,
                            Type = "Terrestrial"
                        },
                        new
                        {
                            Id = 2,
                            DistanceFromStar = 0.71999999999999997,
                            GalaxyId = 1,
                            HasAtmosphere = true,
                            Mass = 0.81499999999999995,
                            Name = "Venus",
                            Radius = 6051.8000000000002,
                            Type = "Terrestrial"
                        },
                        new
                        {
                            Id = 3,
                            DistanceFromStar = 1.0,
                            GalaxyId = 1,
                            HasAtmosphere = true,
                            Mass = 1.0,
                            Name = "Earth",
                            Radius = 6371.0,
                            Type = "Terrestrial"
                        },
                        new
                        {
                            Id = 4,
                            DistanceFromStar = 1.52,
                            GalaxyId = 1,
                            HasAtmosphere = true,
                            Mass = 0.107,
                            Name = "Mars",
                            Radius = 3389.5,
                            Type = "Terrestrial"
                        },
                        new
                        {
                            Id = 5,
                            DistanceFromStar = 5.2000000000000002,
                            GalaxyId = 1,
                            HasAtmosphere = true,
                            Mass = 317.80000000000001,
                            Name = "Jupiter",
                            Radius = 69911.0,
                            Type = "Gas Giant"
                        },
                        new
                        {
                            Id = 6,
                            DistanceFromStar = 9.5399999999999991,
                            GalaxyId = 1,
                            HasAtmosphere = true,
                            Mass = 95.200000000000003,
                            Name = "Saturn",
                            Radius = 58232.0,
                            Type = "Gas Giant"
                        },
                        new
                        {
                            Id = 7,
                            DistanceFromStar = 19.190000000000001,
                            GalaxyId = 1,
                            HasAtmosphere = true,
                            Mass = 14.5,
                            Name = "Uranus",
                            Radius = 25362.0,
                            Type = "Ice Giant"
                        },
                        new
                        {
                            Id = 8,
                            DistanceFromStar = 30.07,
                            GalaxyId = 1,
                            HasAtmosphere = true,
                            Mass = 17.100000000000001,
                            Name = "Neptune",
                            Radius = 24622.0,
                            Type = "Ice Giant"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
