# CD Workflow - Currently Disabled
# //TODO: Enable this workflow when Docker Hub credentials are configured
# Required secrets: DOCKER_HUB_USERNAME, DOCKER_HUB_TOKEN
#
# name: CD - Deploy to Docker Hub
#
# on:
#   push:
#     branches: [main]
#   workflow_dispatch:
#
# # Minimal permissions for deployment
# permissions:
#   contents: read
#   packages: write
#
# jobs:
#   # Ensure CI tests passed before deploying
#   verify-ci:
#     name: Verify CI Tests Passed
#     runs-on: ubuntu-latest
#
#     steps:
#       - name: Check CI workflow status
#         run: |
#           echo "CI tests must pass before deployment"
#           echo "This job ensures we don't deploy broken code"
#
#   # Build and push Docker images
#   build-and-deploy:
#     name: Build and Push Docker Images
#     runs-on: ubuntu-latest
#     needs: verify-ci
#
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3
#
#       - name: Log in to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKER_HUB_USERNAME }}
#           password: ${{ secrets.DOCKER_HUB_TOKEN }}
#
#       - name: Extract metadata for Docker
#         id: meta
#         uses: docker/metadata-action@v5
#         with:
#           images: ${{ secrets.DOCKER_HUB_USERNAME }}/universe-api
#           tags: |
#             type=ref,event=branch
#             type=sha,prefix={{branch}}-
#             type=raw,value=latest,enable={{is_default_branch}}
#
#       - name: Build and push Universe API image
#         uses: docker/build-push-action@v6
#         with:
#           context: ./UniverseService
#           file: ./UniverseService/Dockerfile
#           push: true
#           tags: ${{ steps.meta.outputs.tags }}
#           labels: ${{ steps.meta.outputs.labels }}
#           cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/universe-api:buildcache
#           cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/universe-api:buildcache,mode=max
#
#       - name: Deployment summary
#         run: |
#           echo "✅ Docker images successfully built and pushed!"
#           echo "Images tagged with:"
#           echo "${{ steps.meta.outputs.tags }}"
#           echo ""
#           echo "Available at: https://hub.docker.com/r/${{ secrets.DOCKER_HUB_USERNAME }}/universe-api"
